#!/usr/bin/env python3
"""Density-peak log-curvature finite-q endpoint diagnostic — NO QE runs.

For every material it spherically averages the PBE valence charge density around each
species' atoms, fits ln ρ̄ near the peak to get σ_peak = sqrt(−1/2c₂), and for the fixed
ACTIVE species turns it into the short-range endpoint B_κ = ε⁻¹(κ/σ_peak) for the three
global κ ∈ {0.25, 0.35, 0.50}. κ is a fixed global constant (not tuned per material, not
fitted to gaps); the active species is fixed in qpeak.ACTIVE_SPECIES.

Inputs (all from existing runs):
  * PBE valence charge density + structure  -> runs/<M>/01-pbe-scf/out/<prefix>.save
  * A = 1/ε∞ and μ = hfscreen               -> turboEELS fit (write_comparison.fit_eps)

Outputs:
  results/qpeak_logcurv_endpoint.csv / .md      active-species endpoint table (per material × κ)
  results/qpeak_logcurv_all_species.csv / .md   log-curvature diagnostic for every species

Usage:  python3 scripts/diag_qpeak_logcurv.py
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gen_inputs import finiteg_bexx, q_ws, qcloud_bexx  # noqa: E402
from matlib import ROOT, eels_data, load_materials, pbe_density  # noqa: E402
from qpeak import ACTIVE_SPECIES, KAPPAS, qpeak_bexx, species_sigma  # noqa: E402
from write_comparison import fit_eps  # noqa: E402

RESULTS = ROOT / "results"


def _f(x, nd=4):
    return "" if x is None else f"{x:.{nd}f}"


def _md_table(rows, header):
    out = ["| " + " | ".join(header) + " |",
           "| " + " | ".join("---" for _ in header) + " |"]
    for r in rows:
        out.append("| " + " | ".join(str(c) for c in r) + " |")
    return "\n".join(out)


def main() -> None:
    mats = load_materials()
    endpoint_rows, species_rows = [], []
    warnings = []

    for name, m in mats.items():
        prefix = m["prefix"]
        eps_inf, mu, aexx = fit_eps(eels_data(name, m))
        nval, vol = pbe_density(name, m)
        qws = q_ws(nval, vol)
        fg05 = finiteg_bexx(aexx, 0.5)
        qc05 = qcloud_bexx(aexx, mu, qws, 0.5)

        sig = species_sigma(name, prefix)
        for sp, fdict in sig.items():
            if not fdict["status"].startswith("ok"):
                warnings.append(f"{name}/{sp}: {fdict['status']}")
            species_rows.append([
                name, sp, _f(fdict["r0"], 3), _f(fdict["sigma"], 4),
                _f(fdict["c2"], 4), _f(fdict["R2"], 4), fdict["npts"],
                _f(fdict["thr"], 2), fdict["status"],
            ])

        act = ACTIVE_SPECIES[name]
        fa = sig[act]
        sigma = fa["sigma"]
        for kappa in KAPPAS:
            if sigma is None:
                q_peak = bexx = None
                status = f"FIT FAILED ({fa['status']})"
            else:
                q_peak, bexx = qpeak_bexx(aexx, mu, sigma, kappa)
                if aexx <= bexx <= 1.0:
                    status = "ok"
                else:
                    status = f"WARNING: B_kappa={bexx:.4f} outside [A={aexx:.3f}, 1]"
                    warnings.append(f"{name} kappa={kappa}: {status}")
            endpoint_rows.append([
                name, act, _f(fa["r0"], 3), _f(sigma, 4), _f(fa["c2"], 4),
                _f(fa["R2"], 4), _f(aexx, 4), _f(mu, 4), _f(kappa, 2),
                _f(q_peak, 4), _f(q_peak / mu if q_peak else None, 3), _f(bexx, 4),
                _f(fg05, 4), _f(qc05, 4), "0.2500", status,
            ])

    ep_header = ["material", "active_species", "r0_bohr", "sigma_peak_bohr", "fit_c2",
                 "fit_R2", "A", "mu_bohr^-1", "kappa", "q_peak_bohr^-1", "q_peak/mu",
                 "B_kappa", "finiteG_a0p5_bexx", "qcloud_eta0p5_bexx", "RS-DDH_bexx",
                 "status"]
    sp_header = ["material", "species", "r0_bohr", "sigma_peak_bohr", "fit_c2", "fit_R2",
                 "number_of_fit_points", "fit_window_threshold", "status"]

    RESULTS.mkdir(exist_ok=True)
    _write_csv(RESULTS / "qpeak_logcurv_endpoint.csv", ep_header, endpoint_rows)
    _write_csv(RESULTS / "qpeak_logcurv_all_species.csv", sp_header, species_rows)

    note = ("Density-peak log-curvature finite-q endpoint diagnostic (no QE). "
            "σ_peak = sqrt(−1/2c₂) from ln ρ̄_s(r) ≈ c₀+c₁(r−r₀)+c₂(r−r₀)² near the "
            "spherically-averaged valence-density peak; q_peak = κ/σ_peak; "
            "B_κ = ε⁻¹(q_peak) = 1−(1−A)exp(−q_peak²/4μ²), A=1/ε∞, μ=hfscreen. "
            "κ is a fixed global constant (not per-material, not gap-fitted); the active "
            "species is fixed in qpeak.ACTIVE_SPECIES. finiteG_a0p5 / qcloud_eta0p5 / "
            "RS-DDH(¼) endpoints are shown for comparison. Auto-generated by "
            "scripts/diag_qpeak_logcurv.py.")
    (RESULTS / "qpeak_logcurv_endpoint.md").write_text(
        "# qpeak log-curvature endpoint (active species)\n\n" + note + "\n\n"
        + _md_table(endpoint_rows, ep_header) + "\n")
    (RESULTS / "qpeak_logcurv_all_species.md").write_text(
        "# qpeak log-curvature diagnostic (all species)\n\n"
        "σ_peak per species from the PBE valence density (no QE). "
        "Auto-generated by scripts/diag_qpeak_logcurv.py.\n\n"
        + _md_table(species_rows, sp_header) + "\n")

    for p in ("qpeak_logcurv_endpoint", "qpeak_logcurv_all_species"):
        print(f"wrote results/{p}.csv, results/{p}.md")
    print()
    if warnings:
        print(f"{len(warnings)} warning(s):")
        for w in warnings:
            print("  " + w)
    else:
        print("no warnings — all fits ok and A ≤ B_κ ≤ 1 for every material/κ.")


def _write_csv(path: Path, header, rows):
    with open(path, "w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(header)
        w.writerows(rows)


if __name__ == "__main__":
    main()
